/**
 * HTML content for UI components
 * Auto-generated from figma-ui-panels/
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
 * Edit figma-ui-panels/*.html instead and run the build script
 */

/**
 * HTML content for the JSON Editor UI
 * Auto-generated from json-editor.html
 */
export const JSON_EDITOR_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>JSON Editor</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Fira Code', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      height: 100vh;
      display: flex;
      flex-direction: column;
      background-color: #ffffff;
    }
    
    .toolbar {
      padding: 12px;
      background: #f8f9fa;
      border-bottom: 1px solid #e1e5e9;
      display: flex;
      gap: 8px;
      align-items: center;
    }
    
    .editor-container {
      flex: 1;
      display: flex;
      flex-direction: column;
      position: relative;
    }
    
    .editor {
      flex: 1;
      width: 100%;
      border: none;
      outline: none;
      padding: 16px;
      font-family: 'Fira Code', 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
      font-size: 13px;
      line-height: 1.5;
      resize: none;
      background: #ffffff;
      color: #24292f;
      tab-size: 2;
    }
    
    .editor:focus {
      outline: none;
    }
    
    .btn {
      padding: 6px 12px;
      min-width: 80px;
      border: 1px solid #d0d7de;
      background: #ffffff;
      color: #24292f;
      border-radius: 6px;
      cursor: pointer;
      font-family: inherit;
      font-size: 12px;
      font-weight: 500;
      transition: all 0.15s ease;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 4px;
      height: 35px;
    }
    
    .btn:hover {
      background: #f3f4f6;
      border-color: #afb8c1;
    }
    
    .btn:active {
      background: #e5e7ea;
      transform: translateY(1px);
    }
    
    .btn-primary {
      background: #0969da;
      color: #ffffff;
      border-color: #0969da;
    }
    
    .btn-primary:hover {
      background: #0860ca;
      border-color: #0860ca;
    }
    
    .btn-primary:active {
      background: #0757ba;
    }
    
    .status {
      margin-left: auto;
      font-size: 11px;
      color: #656d76;
      font-weight: 500;
    }
    
    .status.valid {
      color: #1a7f37;
    }
    
    .status.invalid {
      color: #d1242f;
    }
    
    .error-display {
      background: #fff8f8;
      border: 1px solid #f1aeb5;
      border-radius: 6px;
      padding: 8px 12px;
      margin: 8px 16px 16px;
      color: #d1242f;
      font-size: 12px;
      font-family: 'SF Mono', Monaco, monospace;
      white-space: pre-wrap;
      display: none;
    }
    
    .line-numbers {
      position: absolute;
      left: 0;
      top: 0;
      bottom: 0;
      width: 50px;
      color: #656d76;
      font-family: 'Fira Code', 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
      font-size: 13px;
      line-height: 1.5;
      text-align: right;
      padding: 16px 8px;
      border-right: 1px solid #e1e5e9;
      background: #f8f9fa;
      user-select: none;
      pointer-events: none;
      overflow: hidden;
      white-space: pre;
    }
    
    .editor-with-numbers {
      padding-left: 66px;
    }
  </style>
</head>
<body>
  <div class="toolbar">
    <button class="btn" onclick="formatJSON()" title="Format JSON (Ctrl+Shift+F)">
      ✨ Format
    </button>
    <button class="btn" onclick="validateJSON()" title="Validate JSON (Ctrl+Shift+V)">
      ✓ Validate
    </button>
    <button class="btn btn-primary" onclick="saveAndClose()" title="Save and close (Ctrl+S)">
      💾 Save & Close
    </button>
    <button class="btn" onclick="cancel()" title="Cancel (Escape)">
      ✕ Cancel
    </button>
    <div class="status" id="status">Ready</div>
  </div>
  
  <div class="editor-container">
    <div class="line-numbers" id="lineNumbers"></div>
    <textarea 
      class="editor editor-with-numbers" 
      id="editor" 
      placeholder="Enter your JSON here..."
      spellcheck="false"
      autocomplete="off"
      autocorrect="off"
      autocapitalize="off"
    ></textarea>
  </div>
  
  <div class="error-display" id="errorDisplay"></div>
  
  <script>
    let editor = document.getElementById('editor');
    let status = document.getElementById('status');
    let errorDisplay = document.getElementById('errorDisplay');
    let lineNumbers = document.getElementById('lineNumbers');
    let initialContent = '';
    
    // Initialize editor content
    window.addEventListener('message', function(event) {
      if (event.data.pluginMessage && event.data.pluginMessage.type === 'init-content') {
        initialContent = event.data.pluginMessage.content || '';
        editor.value = initialContent;
        updateLineNumbers();
        validateJSON();
        editor.focus();
      }
    });
    
    // Request initial content
    parent.postMessage({
      pluginMessage: { type: 'request-content' }
    }, '*');
    
    // Update line numbers
    function updateLineNumbers() {
      const lines = editor.value.split('\\n');
      const numbers = [];
      for (let i = 1; i <= lines.length; i++) {
        numbers.push(i.toString());
      }
      lineNumbers.textContent = numbers.join('\\n');
    }
    
    // Auto-update line numbers and validation
    editor.addEventListener('input', function() {
      updateLineNumbers();
      validateJSON();
    });
    
    editor.addEventListener('scroll', function() {
      lineNumbers.scrollTop = editor.scrollTop;
    });
    
    // Format JSON
    function formatJSON() {
      try {
        const content = editor.value.trim();
        if (!content) {
          showStatus('Nothing to format', 'invalid');
          return;
        }
        
        const parsed = JSON.parse(content);
        const formatted = JSON.stringify(parsed, null, 2);
        editor.value = formatted;
        updateLineNumbers();
        showStatus('Formatted successfully', 'valid');
        hideError();
      } catch (error) {
        showStatus('Invalid JSON - cannot format', 'invalid');
        showError('Format Error: ' + error.message);
      }
    }
    
    // Validate JSON
    function validateJSON() {
      const content = editor.value.trim();
      
      if (!content) {
        showStatus('Empty', 'invalid');
        hideError();
        return false;
      }
      
      try {
        JSON.parse(content);
        showStatus('Valid JSON ✓', 'valid');
        hideError();
        return true;
      } catch (error) {
        showStatus('Invalid JSON ✗', 'invalid');
        showError('Parse Error: ' + error.message);
        return false;
      }
    }
    
    // Show status
    function showStatus(message, type) {
      status.textContent = message;
      status.className = 'status ' + (type || '');
    }
    
    // Show error
    function showError(message) {
      errorDisplay.textContent = message;
      errorDisplay.style.display = 'block';
    }
    
    // Hide error
    function hideError() {
      errorDisplay.style.display = 'none';
    }
    
    // Save and close
    function saveAndClose() {
      const content = editor.value;
      if (content.trim() && !validateJSON()) {
        if (!confirm('JSON is invalid. Save anyway?')) {
          return;
        }
      }
      
      parent.postMessage({
        pluginMessage: {
          type: 'save-content',
          content: content
        }
      }, '*');
    }
    
    // Cancel
    function cancel() {
      if (editor.value !== initialContent) {
        if (!confirm('You have unsaved changes. Close anyway?')) {
          return;
        }
      }
      
      parent.postMessage({
        pluginMessage: { type: 'cancel' }
      }, '*');
    }
    
    // Keyboard shortcuts
    document.addEventListener('keydown', function(e) {
      if (e.ctrlKey || e.metaKey) {
        switch (e.key) {
          case 's':
            e.preventDefault();
            saveAndClose();
            break;
          case 'f':
            if (e.shiftKey) {
              e.preventDefault();
              formatJSON();
            }
            break;
          case 'v':
            if (e.shiftKey) {
              e.preventDefault();
              validateJSON();
            }
            break;
        }
      } else if (e.key === 'Escape') {
        e.preventDefault();
        cancel();
      } else if (e.key === 'Tab') {
        e.preventDefault();
        const start = editor.selectionStart;
        const end = editor.selectionEnd;
        
        // Insert 2 spaces for tab
        editor.value = editor.value.substring(0, start) + '  ' + editor.value.substring(end);
        editor.selectionStart = editor.selectionEnd = start + 2;
        
        updateLineNumbers();
        validateJSON();
      }
    });
    
    // Auto-resize editor
    function resizeEditor() {
      const toolbar = document.querySelector('.toolbar');
      const error = document.querySelector('.error-display');
      const toolbarHeight = toolbar.offsetHeight;
      const errorHeight = error.style.display === 'none' ? 0 : error.offsetHeight;
      const availableHeight = window.innerHeight - toolbarHeight - errorHeight;
      
      document.querySelector('.editor-container').style.height = availableHeight + 'px';
    }
    
    window.addEventListener('resize', resizeEditor);
    window.addEventListener('load', resizeEditor);
    
    // Initialize
    setTimeout(resizeEditor, 100);
  </script>
</body>
</html> `;

/**
 * HTML content for the HTTP Status Selector UI
 * Auto-generated from status-selector.html
 */
export const STATUS_SELECTOR_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>HTTP Status Selector</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background-color: #f9f9f9;
      padding: 20px 20px 0;
      min-height: 100vh;
      overflow-y: auto;
    }
    
    .container {
      max-width: 440px;
      margin: 0 auto;
    }
    
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 20px;
    }
    
    .title {
      font-size: 18px;
      font-weight: 600;
      color: #333333;
    }
    
    .close-btn {
      background: none;
      border: none;
      font-size: 20px;
      color: #666666;
      cursor: pointer;
      padding: 4px;
      border-radius: 4px;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 28px;
      height: 28px;
    }
    
    .close-btn:hover {
      background: #f0f0f0;
      color: #333333;
    }
    
    .category {
      margin-bottom: 24px;
    }
    
    .category-title {
      font-size: 14px;
      font-weight: 600;
      color: #666666;
      margin-bottom: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .status-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));
      gap: 8px;
    }
    
    .status-button {
      background: white;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 10px 6px;
      cursor: pointer;
      text-align: center;
      transition: all 0.2s ease;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 4px;
      min-height: 45px;
      justify-content: center;
    }
    
    .status-button.current {
      border-color: transparent;
      color: white;
      font-weight: 600;
      transform: translateY(-1px);
      box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
    }

    .status-button.current:hover,
    .status-button:hover {
      color: black;
      background: #f8f9fa;
      border-color: #007AFF;
      transform: translateY(-1px);
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }
    
    .status-code {
      font-size: 14px;
      font-weight: 700;
      letter-spacing: 0.5px;
    }
    
    .status-message {
      font-size: 11px;
      opacity: 0.85;
      font-weight: 500;
    }
    
    /* Success colors */
    .status-2xx {
      background: #4CAF50;
      border-color: #4CAF50;
    }
    
    /* Redirection colors */
    .status-3xx {
      background: #FF9800;
      border-color: #FF9800;
    }
    
    /* Client error colors */
    .status-4xx {
      background: #F44336;
      border-color: #F44336;
    }
    
    /* Server error colors */
    .status-5xx {
      background: #9C27B0;
      border-color: #9C27B0;
    }
    
    @media (max-width: 400px) {
      .status-grid {
        grid-template-columns: repeat(2, 1fr);
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="category">
      <div class="category-title">2xx Success</div>
      <div class="status-grid">
        <button class="status-button" data-status="200" data-class="status-2xx">
          <div class="status-code">200</div>
          <div class="status-message">OK</div>
        </button>
        <button class="status-button" data-status="201" data-class="status-2xx">
          <div class="status-code">201</div>
          <div class="status-message">Created</div>
        </button>
        <button class="status-button" data-status="202" data-class="status-2xx">
          <div class="status-code">202</div>
          <div class="status-message">Accepted</div>
        </button>
        <button class="status-button" data-status="204" data-class="status-2xx">
          <div class="status-code">204</div>
          <div class="status-message">No Content</div>
        </button>
      </div>
    </div>
    
    <div class="category">
      <div class="category-title">3xx Redirection</div>
      <div class="status-grid">
        <button class="status-button" data-status="301" data-class="status-3xx">
          <div class="status-code">301</div>
          <div class="status-message">Moved Permanently</div>
        </button>
        <button class="status-button" data-status="302" data-class="status-3xx">
          <div class="status-code">302</div>
          <div class="status-message">Found</div>
        </button>
        <button class="status-button" data-status="304" data-class="status-3xx">
          <div class="status-code">304</div>
          <div class="status-message">Not Modified</div>
        </button>
      </div>
    </div>
    
    <div class="category">
      <div class="category-title">4xx Client Error</div>
      <div class="status-grid">
        <button class="status-button" data-status="400" data-class="status-4xx">
          <div class="status-code">400</div>
          <div class="status-message">Bad Request</div>
        </button>
        <button class="status-button" data-status="401" data-class="status-4xx">
          <div class="status-code">401</div>
          <div class="status-message">Unauthorized</div>
        </button>
        <button class="status-button" data-status="403" data-class="status-4xx">
          <div class="status-code">403</div>
          <div class="status-message">Forbidden</div>
        </button>
        <button class="status-button" data-status="404" data-class="status-4xx">
          <div class="status-code">404</div>
          <div class="status-message">Not Found</div>
        </button>
        <button class="status-button" data-status="405" data-class="status-4xx">
          <div class="status-code">405</div>
          <div class="status-message">Method Not Allowed</div>
        </button>
        <button class="status-button" data-status="409" data-class="status-4xx">
          <div class="status-code">409</div>
          <div class="status-message">Conflict</div>
        </button>
        <button class="status-button" data-status="422" data-class="status-4xx">
          <div class="status-code">422</div>
          <div class="status-message">Unprocessable Entity</div>
        </button>
        <button class="status-button" data-status="429" data-class="status-4xx">
          <div class="status-code">429</div>
          <div class="status-message">Too Many Requests</div>
        </button>
      </div>
    </div>
    
    <div class="category">
      <div class="category-title">5xx Server Error</div>
      <div class="status-grid">
        <button class="status-button" data-status="500" data-class="status-5xx">
          <div class="status-code">500</div>
          <div class="status-message">Internal Server Error</div>
        </button>
        <button class="status-button" data-status="501" data-class="status-5xx">
          <div class="status-code">501</div>
          <div class="status-message">Not Implemented</div>
        </button>
        <button class="status-button" data-status="502" data-class="status-5xx">
          <div class="status-code">502</div>
          <div class="status-message">Bad Gateway</div>
        </button>
        <button class="status-button" data-status="503" data-class="status-5xx">
          <div class="status-code">503</div>
          <div class="status-message">Service Unavailable</div>
        </button>
        <button class="status-button" data-status="504" data-class="status-5xx">
          <div class="status-code">504</div>
          <div class="status-message">Gateway Timeout</div>
        </button>
      </div>
    </div>
  </div>
  
  <script>
    let currentStatus = 200;
    
    // Initialize the selector
    window.addEventListener('message', function(event) {
      if (event.data.pluginMessage && event.data.pluginMessage.type === 'init-status-selector') {
        currentStatus = event.data.pluginMessage.currentStatus || 200;
        highlightCurrentStatus();
      }
    });
    
    // Request initial data when loaded
    parent.postMessage({
      pluginMessage: { type: 'request-current-status' }
    }, '*');
    
    // Highlight the current status
    function highlightCurrentStatus() {
      const buttons = document.querySelectorAll('.status-button');
      buttons.forEach(button => {
        const status = parseInt(button.dataset.status);
        const statusClass = button.dataset.class;
        
        if (status === currentStatus) {
          button.classList.add('current', statusClass);
        } else {
          button.classList.remove('current', statusClass);
        }
      });
    }
    
    // Handle status selection
    document.addEventListener('click', function(event) {
      if (event.target.closest('.status-button')) {
        const button = event.target.closest('.status-button');
        const status = parseInt(button.dataset.status);
        
        // Send the selected status back to the widget
        parent.postMessage({
          pluginMessage: {
            type: 'status-selected',
            status: status
          }
        }, '*');
      }
    });
    
    // Handle close button
    function closeSelector() {
      parent.postMessage({
        pluginMessage: { type: 'status-selector-closed' }
      }, '*');
    }
    
    // Handle keyboard shortcuts
    document.addEventListener('keydown', function(event) {
      if (event.key === 'Escape') {
        closeSelector();
      }
    });
  </script>
</body>
</html> `;

