const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, '../templates/json-editor.html');
const outputPath = path.join(__dirname, '../widget-src/utils/htmlLoader.ts');

try {
  // Read the HTML file
  const htmlContent = fs.readFileSync(htmlPath, 'utf8');
  
  // Escape backticks and other special characters for template literal
  const escapedContent = htmlContent
    .replace(/\\/g, '\\\\')  // Escape backslashes
    .replace(/`/g, '\\`')    // Escape backticks
    .replace(/\${/g, '\\${'); // Escape template literal expressions
  
  // Generate the TypeScript file
  const tsContent = `/**
 * HTML content for the JSON Editor UI
 * Auto-generated from templates/json-editor.html
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
 * Edit templates/json-editor.html instead and run the build script
 */

export const JSON_EDITOR_HTML = \`${escapedContent}\`;
`;
  
  // Write the TypeScript file
  fs.writeFileSync(outputPath, tsContent, 'utf8');
  
  console.log('✅ HTML content embedded into widget-src/utils/htmlLoader.ts');
} catch (error) {
  console.error('❌ Error embedding HTML content:', error.message);
  process.exit(1);
} 