const fs = require('fs');
const path = require('path');

// Define template configurations
const uiPanels = [
  {
    name: 'JSON_EDITOR_HTML',
    inputPath: path.join(__dirname, '../figma-ui-panels/json-editor.html'),
    description: 'HTML content for the JSON Editor UI'
  },
  {
    name: 'STATUS_SELECTOR_HTML',
    inputPath: path.join(__dirname, '../figma-ui-panels/status-selector.html'),
    description: 'HTML content for the HTTP Status Selector UI'
  }
];

const outputPath = path.join(__dirname, '../widget-src/shared/utils/htmlLoader.ts');

try {
  let tsContent = `/**
 * HTML content for UI components
 * Auto-generated from figma-ui-panels/
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
 * Edit figma-ui-panels/*.html instead and run the build script
 */

`;

  // Process each UI panel
  uiPanels.forEach(panel => {
    // Read the HTML file
    const htmlContent = fs.readFileSync(panel.inputPath, 'utf8');
    
    // Escape backticks and other special characters for template literal
    const escapedContent = htmlContent
      .replace(/\\/g, '\\\\')  // Escape backslashes
      .replace(/`/g, '\\`')    // Escape backticks
      .replace(/\${/g, '\\${'); // Escape template literal expressions
    
    // Add to TypeScript content
    tsContent += `/**
 * ${panel.description}
 * Auto-generated from ${path.basename(panel.inputPath)}
 */
export const ${panel.name} = \`${escapedContent}\`;

`;
  });
  
  // Write the TypeScript file
  fs.writeFileSync(outputPath, tsContent, 'utf8');
  
  console.log('✅ HTML content embedded into widget-src/shared/utils/htmlLoader.ts');
  console.log(`   - ${uiPanels.length} UI panel(s) processed:`);
  uiPanels.forEach(panel => {
    console.log(`     • ${panel.name} from ${path.basename(panel.inputPath)}`);
  });
} catch (error) {
  console.error('❌ Error embedding HTML content:', error.message);
  process.exit(1);
} 